### ISSUE TITLE
python3 refreshMetadata.py Error

### ISSUE THREAD

**Issue by itanivalkyrie** [Inervo/BedethequeKomga#4]
Hello,
I just installed the repo and try to run and this error appened. 

```
Traceback (most recent call last):
  File "/home/docker1/komgabdtek/BedethequeKomga/refreshMetadata.py", line 4, in <module>
    from bedethequeApi import bedethequeApiProxies, find_series_url, get_comic_series_metadata, \
  File "/home/docker1/komgabdtek/BedethequeKomga/bedethequeApi.py", line 195
    match block.text.strip():
          ^
SyntaxError: invalid syntax
```

Version of Python : 3.11

I try to update metadata from Spy X Family 
https://www.bedetheque.com/serie-71084-BD-Spy-x-Family.html

Same error with Library List

```
# Mandatory fields - Status of the series to update
# By default, 'ONGOING', 'HIATUS' to limit the requests to Bedetheque
KOMGA_STATUS = ['ONGOING', 'HIATUS'] # Accept ONGOING HIATUS ABANDONED and/or ENDED

# Optionnal fields. If empty, will refresh all the books on komga
# Only on these 3 fields can be completed. If more than 1 is, it will generate an error
KOMGA_LIBRARY_LIST = ['0D6EMQ419JRHS'] # retrieve library value from library URL in Komga. Exemple : ['0D10T0X04WXY9', '0D10GBGK4WJZW']
KOMGA_COLLECTION_LIST = [] # retrieve collection value from collection URL in Komga. Exemple : ['0D10T0X04WXY9', '0D10GBGK4WJZW']
KOMGA_SERIE_LIST = [] # retrieve serie value from serie URL in Komga. Exemple : ['0D10T0X04WXY9', '0D10GBGK4WJZW']

# Optionnal. Set this to True to refresh only series (not books of a series)
SERIES_ONLY = False

# Optionnal. Do not use proxies, but a delay between each request. Default:7 (seconds)
WAIT_DELAY = 7
USE_PROXIES = True
```

**Comment by Inervo** [comment]
Hi,

This is strange, because this error is usually due to the "match" not being recognized by python, ie. using a version prior to 3.10.

No reason why this error should appear with python 3.11.
Can you try to check again with python -v please ?

**Comment by itanivalkyrie** [comment]
```
root@nas-itani:/home/docker1/komgabdtek/BedethequeKomga# python3 --version
Python 3.9.2
root@nas-itani:/home/docker1/komgabdtek/BedethequeKomga# python --version
-bash: python : commande introuvable
root@nas-itani:/home/docker1/komgabdtek/BedethequeKomga# python3.11 --version
Python 3.11.1
```
Forcing using python3.11 solve the problem. 

```
Solution :
pip3.11 install -r requirements.txt
python3.11 refreshMetadata.py
```

Sorry for wasting your time 👍

**Comment by Inervo** [comment]
No worries, enjoy ! :)

**Comment by itanivalkyrie** [comment]
Another error i encounter FYI. 
Don't know what can i do with this. Don't want to be ban :-D
![image](https://github.com/Inervo/BedethequeKomga/assets/2438572/2aea0d64-1a01-494c-b0fe-633bb271e260)

**Comment by Inervo** [comment]
Yeah, lately, the working free proxies are rare to non existent...

One option is USE_PROXIES = False in the config file, and keep a delay of 7s, the ban should not append (but no guarantee. Worked for me, and it's the standard for some other tools, but you never know...)

**Comment by itanivalkyrie** [comment]
Ok. I'll try this with a 10 sec delay to be sure.
