### ISSUE TITLE
[BUG] SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by Dimen7io** [Inervo/BedethequeKomga#5]
Hello , running the script with python 3.11.5 i get  

C:\scripts\BedethequeKomga-main>py refreshMetadata.py

Traceback (most recent call last):
  File "C:\scripts\BedethequeKomga-main\refreshMetadata.py", line 2, in <module>
    from env import InitEnv
  File "C:\scripts\BedethequeKomga-main\env.py", line 2, in <module>
    from config import *
  File "C:\scripts\BedethequeKomga-main\config.py", line 12
    KOMGA_LIBRARY_LIST = [0DG3TJ4SPEQ8Q] # retrieve library value from library URL in Komga. Exemple : ['0D10T0X04WXY9', '0D10GBGK4WJZW']
                          ^
SyntaxError: invalid decimal

 
Thank you for your help

**Comment by Inervo** [comment]
Hi,

Please set your komga library list value between single quote `['VALUE']`, as in the examples.

Best regards
